/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { LoanerContract } from "./Loaner";
import { MigrationsContract } from "./Migrations";
import { SimpleStorageContract } from "./SimpleStorage";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Loaner"): LoanerContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "SimpleStorage"): SimpleStorageContract;
    }
  }
}

export { LoanerContract, LoanerInstance } from "./Loaner";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { SimpleStorageContract, SimpleStorageInstance } from "./SimpleStorage";
